// src/screens/LoginScreen/styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  gradient: { flex: 1 },
  container: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 25,
    paddingVertical: 40,
  },
  header: { alignItems: 'center', marginBottom: 30 },
  title: { fontSize: 26, fontWeight: 'bold', color: '#4F4F4F', marginTop: 10 },
  subtitle: { fontSize: 15, color: '#6B7280', marginTop: 4 },
  input: {
    width: '100%',
    height: 52,
    backgroundColor: '#FFF',
    borderRadius: 30,
    paddingHorizontal: 18,
    fontSize: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    color: '#333',
  },
  linkContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 25,
  },
  link: { color: '#4F8A8B', fontWeight: '500', fontSize: 14 },
  loginButton: {
    width: '100%',
    backgroundColor: '#6BA292',
    paddingVertical: 15,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom: 25,
    shadowColor: '#6BA292',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  loginButtonText: { color: '#FFF', fontSize: 18, fontWeight: '600' },
  dividerContainer: { flexDirection: 'row', alignItems: 'center', marginVertical: 10 },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#DDD' },
  dividerText: { marginHorizontal: 10, color: '#999', fontSize: 13 },
  socialContainer: { flexDirection: 'row', justifyContent: 'center', marginTop: 10 },
  socialButton: {
    backgroundColor: '#FFF',
    padding: 12,
    borderRadius: 50,
    marginHorizontal: 10,
    borderWidth: 1.5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
});
