import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  gradient: { flex: 1 },
  container: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 25,
    paddingVertical: 40,
  },
  header: { alignItems: 'center', marginBottom: 25 },
  title: { fontSize: 28, fontWeight: '700', color: '#2F4F4F', marginTop: 10 },
  subtitle: { fontSize: 15, color: '#6B7280', marginTop: 4, textAlign: 'center' },
  input: {
    width: '100%',
    backgroundColor: '#FFF',
    borderRadius: 25,
    paddingHorizontal: 18,
    paddingVertical: 12,
    fontSize: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  multiline: {
    height: 100,
    textAlignVertical: 'top',
  },
  dropdownContainer: { width: '100%', marginBottom: 15 },
  dropdownButton: {
    backgroundColor: '#FFF',
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderRadius: 25,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  dropdownText: { fontSize: 15, color: '#000' },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    padding: 20,
  },
  dropdownList: {
    backgroundColor: '#FFF',
    borderRadius: 10,
    maxHeight: 300,
    paddingVertical: 10,
  },
  dropdownItem: { paddingVertical: 10, paddingHorizontal: 15 },
  dropdownItemText: { fontSize: 16, color: '#333' },
  uploadButton: { width: '100%', backgroundColor: '#FFF', paddingVertical: 15, borderRadius: 25, alignItems: 'center', marginBottom: 20, borderWidth: 1, borderColor: '#6BA292' },
  uploadButtonText: { color: '#6BA292', fontSize: 16 },
});
